from setuptools import setup, find_packages

setup(
    name='global_settings',
    version='1.0',
    description="A package for managing global settings",
    url="https://github.com/your_username/global_settings",
    author="Leonardo Ortega Hernandez",
    packages=find_packages(),
    author_email="leon9894@gmail.com",
    license="MIT",
    install_requires=[
        'Django>=2.2',
    ],
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.0',
        'Programming Language :: Python :: 3.1',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    keywords="global settings configuration",
    python_requires=">=3.0",
)
