# Generated by Django 2.2.2 on 2023-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, help_text="save the value with json.dumps'", null=True)),
                ('type', models.CharField(choices=[('int', 'integer'), ('list', 'list'), ('dict', 'dictionary'), ('float', 'float'), ('str', 'string')], default='str', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
